
################################################################################################################ 
########### GOAL PROVIDER
################################################################################################################

/goal_manager/goal_provider:
  ros__parameters:

    frame_id: 'odom'

    goals: '[[0.0, 1.0, 1.0],
             [1.0, 1.0, 1.0]]'

    debug: True                   # Enable debug prints for troubleshooting
    unit_test: True               # Allow the node to run isolated for unit testing
    use_sim_time: False


/goal_manager/goal_reached:
  ros__parameters:

    robot_in_goal_tolerance: 0.3  # Tolerance for determining if the robot has reached its goal, in meters

    debug: True                   # Enable debug prints for troubleshooting
    unit_test: True               # Allow the node to run isolated for unit testing
    use_sim_time: False