


################################################################################################################ 
########### GOAL PROVIDER
################################################################################################################

/goal_manager/goal_provider:  
  ros__parameters:

    frame_id: 'odom'   

    goals: '[ [3.236, -2.185, 1.0], 
              [12.025, -8.053, 0.0], 
              [10.5737, -4.52506, 2.0],
              [10.5737, -2.03166, 2.0],
              [11.6, -0.646, 0.0],
              [6.3782, 0.42339, 2.0],
              [0.0, 0.0, 2.0],
              [-0.5048, -1.485, 3.0], 
              [-0.5047, -3.673, 3.0], 
              [-0.105, -6.160, 0.0]]'

    # goals: '[[2.0, 1.0, 0.0], 
    #          [4.0, 0.0, 0.0], 
    #          [6.0, 1.0, 0.0], 
    #          [8.0, 0.0, 0.0], 
    #          [10.0, 1.0, 0.0]]'          

#    goals: '[[ 2.89, -2.20,  1.0],
#             [ 6.29, -6.17,  3.0],
#             [12.46, -6.62,  0.0],
#             [10.31, -5.42,  3.0], 
#             [10.47, -3.12,  3.0],
#             [12.03, -0.98,  0.0], 
#             [ 4.83,  0.70,  3.0],
#             [ 1.78, -0.97, 3.0],  
#             [ 1.74, -4.04, 3.0],
#             [ 2.46, -5.88, 0.0]]'

            #  [7.94104, -7.30343, 3.0],
    # goals: '[[3.236, -2.185, 1.0], 
    #          [8.52931, -5.42682, 2.0],
    #          [12.025, -7.053, 0.0],
    #          [10.2737, -4.52506, 2.0], 
    #          [10.3661, -2.03166, 2.0], 
    #          [11.6, -0.646, 0.0], 
    #          [10.4665, 0.538036, 2.0],
    #          [8.52931, -5.42682, 2.0], 
    #          [-1.048, -1.485, 3.0], 
    #          [-1.247, -3.673, 3.0], 
    #          [-0.195, -6.160, 0.0]]'

    
    # goals: '[[2.0, 0.0, 0.0], 
    #          [4.0, 0.0, 2.0], 
    #          [4.0, -4.0, 0.0]]'

    debug: True                    # Enable debug prints for troubleshooting
    use_global_param: True               # Allow the node to run isolated for unit testing
    use_sim_time: False
    frequency: 6                   # Node frequency 


################################################################################################################ 
########### GOAL REACHED
################################################################################################################


/goal_manager/goal_reached:
  ros__parameters:

    # Tolerance for determining if the robot has reached its GHOST goal, in meters
    high_accuracy: 0.15
    normal_accuracy: 0.30
    low_accuracy: 0.65

     # Tolerance for determining if the robot has reached its WAYPOINT goal, in meters
    waypoint_goal_tolerance: 0.30  

    debug: True                   # Enable debug prints for troubleshooting
    use_global_param: True               # Allow the node to run isolated for unit testing
    use_sim_time: False
    frequency: 6 

