################################################################################################################ 
########### GOAL PROVIDER
################################################################################################################

/goal_manager/goal_provider:  
  ros__parameters:

    frame_id: 'odom'   

    goals: '[[ 7.22, -0.5,  2.0],
             [ 11.05, -0.5, 2.0],
             [ 17.09, -0.5, 2.0],
             [ 25.16, 0.3, 0.0], 
             [ 19.35, -1.52, 1.0], 
             [17.53, -2.35, 1.0],
             [10.34, -4.71, 1.0], 
             [5.94, -7.41, 1.0],
             [-0.05, -8.56, 0.0],
             [-1.07, -10.33, 1.0],
             [1.156, -11.11, 1.0], 
             [5.036, -11.08, 1.0],
             [6.46, -10.66, 1.0],
             [9.51, -9.43, 1.0],
             [10.48, -9.027, 0.0],
             [ 0.0, 0.0, 0.0]]'


#             [6.24, -7.96, 3.0],
#             [8.06, -5.94, 2.0],
#             [9.55, -5.85, 2.0],
#             [11.93, -6.63, 1.0],
#             [12.31, -8.07, 1.0],
#             [12.236, -8.32623, 1.0],
#             [11.12, -10.97, 0.0]]' 

    debug: false                    # Enable debug prints for troubleshooting
    use_global_param: True               # Allow the node to run isolated for unit testing
    use_sim_time: False
    frequency: 6                   # Node frequency 


################################################################################################################ 
########### GOAL REACHED
################################################################################################################


/goal_manager/goal_reached:
  ros__parameters:

    # Tolerance for determining if the robot has reached its GHOST goal, in meters
    high_accuracy: 0.15
    normal_accuracy: 0.70
    low_accuracy: 1.0

     # Tolerance for determining if the robot has reached its WAYPOINT goal, in meters
    waypoint_goal_tolerance: 0.35

    debug: false                   # Enable debug prints for troubleshooting
    use_global_param: True               # Allow the node to run isolated for unit     
    use_sim_time: False
    frequency: 6

